// @vitest-environment node

import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, it } from "vitest";

import { sharedBitInventory } from "../../src/catalog/inventory.generated";
import { HELPER_NAMES } from "../../src/catalog/bit-schema";
import { CATEGORY_LABELS } from "../generate-docs.mjs";
import {
  CATEGORY_ORDER,
  extractExportedApis,
  generateSkillRefs,
  parseCompositionVariables,
} from "../generate-skill-refs.mjs";

const projectRoot = path.resolve(
  fileURLToPath(new URL("../..", import.meta.url)),
);

describe("generate-skill-refs", () => {
  it("writes bits.md covering every inventory bit grouped by category", async () => {
    const result = await generateSkillRefs();
    const bitsMarkdown = await readFile(
      path.join(projectRoot, "skills", "hyperbits", "references", "bits.md"),
      "utf8",
    );

    expect(result.bits).toHaveLength(sharedBitInventory.length);
    expect(bitsMarkdown).toContain(
      "Generated by `scripts/generate-skill-refs.mjs`",
    );

    for (const category of CATEGORY_ORDER) {
      expect(bitsMarkdown).toContain(
        `## ${CATEGORY_LABELS[category as keyof typeof CATEGORY_LABELS]}`,
      );
    }

    for (const entry of sharedBitInventory) {
      expect(bitsMarkdown).toContain(`### \`${entry.id}\``);
      expect(bitsMarkdown).toContain(entry.description);
      expect(bitsMarkdown).toContain(entry.sourcePath);

      const knobs = parseCompositionVariables(entry.sourceCode);
      if (knobs.length === 0) {
        const blockStart = bitsMarkdown.indexOf(`### \`${entry.id}\``);
        const blockEnd = bitsMarkdown.indexOf("\n### `", blockStart + 1);
        const block = bitsMarkdown.slice(
          blockStart,
          blockEnd === -1 ? undefined : blockEnd,
        );
        expect(block).toContain("Knobs (`data-composition-variables`): none");
      } else {
        for (const knob of knobs) {
          expect(bitsMarkdown).toContain(`\`${knob.id}\``);
        }
      }
    }
  });

  it("writes helpers.md with every exported helper API from sources", async () => {
    const result = await generateSkillRefs();
    const helpersMarkdown = await readFile(
      path.join(projectRoot, "skills", "hyperbits", "references", "helpers.md"),
      "utf8",
    );

    expect(helpersMarkdown).toContain(
      "Generated by `scripts/generate-skill-refs.mjs`",
    );
    expect(helpersMarkdown).toContain("HYPERBITS_GSAP_CDN");

    for (const helperName of HELPER_NAMES) {
      expect(helpersMarkdown).toContain(`## ${helperName}`);
    }

    const exportedNames = new Set<string>();
    for (const section of result.helperSections) {
      for (const api of section.apis) {
        exportedNames.add(api.name);
        expect(helpersMarkdown).toContain(`### \`${api.name}\``);
      }
    }

    expect(exportedNames.has("interpolate")).toBe(true);
    expect(exportedNames.has("stagger")).toBe(true);
    expect(exportedNames.has("viewport")).toBe(true);
    expect(exportedNames.has("createParticles")).toBe(true);
    expect(exportedNames.has("createScene3D")).toBe(true);
    expect(exportedNames.has("createCounter")).toBe(true);
    expect(exportedNames.has("typewriter")).toBe(true);
    expect(exportedNames.has("createCodeBlock")).toBe(true);

    const interpolateSource = await readFile(
      path.join(projectRoot, "src", "helpers", "interpolate.ts"),
      "utf8",
    );
    const interpolateApis = extractExportedApis(
      "interpolate.ts",
      interpolateSource,
    );
    for (const api of interpolateApis) {
      expect(exportedNames.has(api.name)).toBe(true);
    }
  });

  it("is idempotent", async () => {
    const first = await generateSkillRefs();
    const second = await generateSkillRefs();
    expect(second.bitsMarkdown).toBe(first.bitsMarkdown);
    expect(second.helpersMarkdown).toBe(first.helpersMarkdown);
  });
});
