#!/usr/bin/env node

import { copyFile, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  CATEGORY_LABELS,
  GSAP_CDN,
  bitHtmlPath,
  listBitJsonFiles,
  projectRoot,
  readBitManifest,
} from "./lib/bits.mjs";

export { CATEGORY_LABELS };

const docsRoot = path.join(projectRoot, "docs");
const bitsMdxDir = path.join(docsRoot, "src", "content", "docs", "bits");
const publicBitsDir = path.join(docsRoot, "public", "bits");
const publicVendorDir = path.join(docsRoot, "public", "vendor");
const generatedCatalogPath = path.join(
  docsRoot,
  "src",
  "lib",
  "bits.generated.ts",
);

const IIFE_PUBLIC_PATH = "/vendor/hyperbits.iife.js";

const escapeMdx = (value) =>
  value.replaceAll("&", "&amp;").replaceAll("<", "&lt;").replaceAll(">", "&gt;");

const preparePlaygroundHtml = (html) => {
  let prepared = html.replaceAll(
    'src="hyperbits.iife.js"',
    `src="${IIFE_PUBLIC_PATH}"`,
  );
  if (!prepared.includes("gsap@") && !prepared.includes("gsap.min.js")) {
    prepared = prepared.replace(
      "<head>",
      `<head>\n    <script src="${GSAP_CDN}"></script>`,
    );
  }
  return prepared;
};

const yamlQuote = (value) => `"${value.replaceAll("\\", "\\\\").replaceAll('"', '\\"')}"`;

const bitMdx = (bit) => `---
title: ${yamlQuote(bit.title)}
category: ${yamlQuote(bit.categoryLabel)}
description: ${yamlQuote(bit.description)}
---
import { BitPlayground } from '@components/BitPlayground';

${escapeMdx(bit.description)}.

<BitPlayground client:only="react" bitName="${bit.id}" />
`;

const copyVendorFiles = async () => {
  await mkdir(publicVendorDir, { recursive: true });

  const iifeSrc = path.join(projectRoot, "dist", "hyperbits.iife.js");
  try {
    await copyFile(iifeSrc, path.join(publicVendorDir, "hyperbits.iife.js"));
  } catch (error) {
    if (error && error.code === "ENOENT") {
      console.warn(
        "dist/hyperbits.iife.js is missing; playground helper scripts will 404 until npm run build.",
      );
    } else {
      throw error;
    }
  }

  const playerDest = path.join(
    publicVendorDir,
    "hyperframes-player.global.js",
  );
  const playerCandidates = [
    path.join(publicVendorDir, "hyperframes-player.global.js"),
    "/tmp/hf/package/dist/hyperframes-player.global.js",
    path.join(
      projectRoot,
      "node_modules",
      "hyperframes",
      "dist",
      "hyperframes-player.global.js",
    ),
  ];

  let playerSource = null;
  for (const candidate of playerCandidates) {
    try {
      await readFile(candidate);
      playerSource = candidate;
      break;
    } catch {
      // try the next candidate
    }
  }

  if (playerSource && playerSource !== playerDest) {
    await copyFile(playerSource, playerDest);
  } else if (!playerSource) {
    throw new Error(
      "hyperframes-player.global.js not found. Expected /tmp/hf/package/dist/hyperframes-player.global.js",
    );
  }
};

const pruneGeneratedBits = async (keepIds) => {
  for (const dirPath of [bitsMdxDir, publicBitsDir]) {
    let entries;
    try {
      entries = await readdir(dirPath, { withFileTypes: true });
    } catch (error) {
      if (error && error.code === "ENOENT") {
        continue;
      }
      throw error;
    }

    for (const entry of entries) {
      if (!entry.isFile()) {
        continue;
      }
      const id = entry.name.replace(/\.(mdx|html)$/, "");
      if (!keepIds.has(id)) {
        await rm(path.join(dirPath, entry.name), { force: true });
      }
    }
  }
};

const generatedCatalogSource = (bits) => {
  const serialized = JSON.stringify(bits, null, 2);
  return `/* eslint-disable */
// Generated by scripts/generate-docs.mjs. Do not edit.

export type DocsBit = {
  id: string;
  name: string;
  title: string;
  description: string;
  category: string;
  categoryLabel: string;
  tags: string[];
  duration: number;
  width: number;
  height: number;
  helpers: string[];
  htmlPath: string;
};

export const docsBits: DocsBit[] = ${serialized};

export const docsBitsById: Record<string, DocsBit> = Object.fromEntries(
  docsBits.map((bit) => [bit.id, bit]),
);
`;
};

export const generateDocs = async () => {
  const bitFiles = await listBitJsonFiles();
  const bits = [];

  await mkdir(bitsMdxDir, { recursive: true });
  await mkdir(publicBitsDir, { recursive: true });
  await mkdir(path.dirname(generatedCatalogPath), { recursive: true });

  for (const bitJsonPath of bitFiles) {
    const manifest = await readBitManifest(bitJsonPath);
    const bitDir = path.dirname(bitJsonPath);
    const category = path.basename(path.dirname(bitDir));
    const categoryLabel = CATEGORY_LABELS[category] ?? category;
    const html = await readFile(bitHtmlPath(bitJsonPath), "utf8");

    const bit = {
      id: manifest.name,
      name: manifest.title,
      title: manifest.title,
      description: manifest.description,
      category,
      categoryLabel,
      tags: [...manifest.tags],
      duration: manifest.duration,
      width: manifest.width,
      height: manifest.height,
      helpers: [...(manifest.helpers ?? [])],
      htmlPath: `/bits/${manifest.name}.html`,
    };
    bits.push(bit);

    await writeFile(path.join(bitsMdxDir, `${bit.id}.mdx`), bitMdx(bit));
    await writeFile(
      path.join(publicBitsDir, `${bit.id}.html`),
      preparePlaygroundHtml(html),
    );
  }

  await pruneGeneratedBits(new Set(bits.map((bit) => bit.id)));
  await copyVendorFiles();
  await writeFile(generatedCatalogPath, generatedCatalogSource(bits));

  return bits;
};

const main = async () => {
  const bits = await generateDocs();
  console.log(`Generated docs for ${bits.length} bit(s).`);
};

if (
  process.argv[1] &&
  fileURLToPath(import.meta.url) === path.resolve(process.argv[1])
) {
  main().catch((error) => {
    console.error(error instanceof Error ? error.message : String(error));
    process.exit(1);
  });
}
