/* eslint-disable */
// Generated by scripts/generate-docs.mjs. Do not edit.

export type DocsBit = {
  id: string;
  name: string;
  title: string;
  description: string;
  category: string;
  categoryLabel: string;
  tags: string[];
  duration: number;
  width: number;
  height: number;
  helpers: string[];
  htmlPath: string;
};

export const docsBits: DocsBit[] = [
  {
    "id": "conic-gradient",
    "name": "Conic Gradient",
    "title": "Conic Gradient",
    "description": "Colorful conic gradient rotation",
    "category": "background-effects",
    "categoryLabel": "Background Effects",
    "tags": [
      "background",
      "gradient",
      "conic",
      "rainbow"
    ],
    "duration": 2,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "gradient"
    ],
    "htmlPath": "/bits/conic-gradient.html"
  },
  {
    "id": "linear-gradient",
    "name": "Linear Gradient",
    "title": "Linear Gradient",
    "description": "Smooth transition between linear gradients",
    "category": "background-effects",
    "categoryLabel": "Background Effects",
    "tags": [
      "background",
      "gradient",
      "linear"
    ],
    "duration": 3,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "gradient"
    ],
    "htmlPath": "/bits/linear-gradient.html"
  },
  {
    "id": "radial-gradient",
    "name": "Radial Gradient",
    "title": "Radial Gradient",
    "description": "Smooth transition between radial gradients",
    "category": "background-effects",
    "categoryLabel": "Background Effects",
    "tags": [
      "background",
      "gradient",
      "radial"
    ],
    "duration": 3,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "gradient"
    ],
    "htmlPath": "/bits/radial-gradient.html"
  },
  {
    "id": "feature-showcase",
    "name": "Hyperbits",
    "title": "Hyperbits",
    "description": "Promotional showcase for the hyperbits catalog of HyperFrames animation bits.",
    "category": "full-compositions",
    "categoryLabel": "Full Compositions",
    "tags": [
      "showcase",
      "promo",
      "library"
    ],
    "duration": 38,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "text",
      "stagger",
      "gradient",
      "particles",
      "scene3d",
      "code",
      "viewport"
    ],
    "htmlPath": "/bits/feature-showcase.html"
  },
  {
    "id": "fireflies",
    "name": "Fireflies",
    "title": "Fireflies",
    "description": "Wandering particles with glow effect simulating fireflies",
    "category": "particles",
    "categoryLabel": "Particles",
    "tags": [
      "particles",
      "nature",
      "ambient",
      "animation"
    ],
    "duration": 10,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "particles",
      "viewport"
    ],
    "htmlPath": "/bits/fireflies.html"
  },
  {
    "id": "particles-fountain",
    "name": "Fountain",
    "title": "Fountain",
    "description": "Bursting fountain particles effect",
    "category": "particles",
    "categoryLabel": "Particles",
    "tags": [
      "particles",
      "burst",
      "fountain"
    ],
    "duration": 6,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "particles",
      "viewport"
    ],
    "htmlPath": "/bits/particles-fountain.html"
  },
  {
    "id": "particles-grid",
    "name": "Grid Particles",
    "title": "Grid Particles",
    "description": "Particles snapping to a grid",
    "category": "particles",
    "categoryLabel": "Particles",
    "tags": [
      "particles",
      "grid",
      "snap"
    ],
    "duration": 6.67,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "particles",
      "viewport"
    ],
    "htmlPath": "/bits/particles-grid.html"
  },
  {
    "id": "particles-snow",
    "name": "Snow",
    "title": "Snow",
    "description": "Falling snow particles effect",
    "category": "particles",
    "categoryLabel": "Particles",
    "tags": [
      "particles",
      "snow",
      "weather"
    ],
    "duration": 10,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "particles",
      "viewport"
    ],
    "htmlPath": "/bits/particles-snow.html"
  },
  {
    "id": "scrolling-columns",
    "name": "Scrolling Columns",
    "title": "Scrolling Columns",
    "description": "Four columns of images scrolling with different speeds in a panning 3D scene",
    "category": "particles",
    "categoryLabel": "Particles",
    "tags": [
      "particles",
      "3d",
      "scrolling",
      "columns"
    ],
    "duration": 10,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "viewport",
      "random"
    ],
    "htmlPath": "/bits/scrolling-columns.html"
  },
  {
    "id": "3d-basic",
    "name": "Basic 3D Scene",
    "title": "Basic 3D Scene",
    "description": "3D camera transitions between positioned steps, impress.js style",
    "category": "scenes-3d",
    "categoryLabel": "3D Scenes",
    "tags": [
      "3d",
      "camera",
      "presentation",
      "transition"
    ],
    "duration": 5,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "scene3d",
      "viewport"
    ],
    "htmlPath": "/bits/3d-basic.html"
  },
  {
    "id": "3d-elements",
    "name": "3D Elements",
    "title": "3D Elements",
    "description": "3D Scene allows placing arbitrary elements in 3D space",
    "category": "scenes-3d",
    "categoryLabel": "3D Scenes",
    "tags": [
      "3d",
      "camera",
      "presentation",
      "transition"
    ],
    "duration": 6.67,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "scene3d",
      "random",
      "viewport"
    ],
    "htmlPath": "/bits/3d-elements.html"
  },
  {
    "id": "carousel",
    "name": "3D Carousel",
    "title": "3D Carousel",
    "description": "Rotating carousel of cards in 3D space",
    "category": "scenes-3d",
    "categoryLabel": "3D Scenes",
    "tags": [
      "3d",
      "carousel",
      "gallery",
      "animation"
    ],
    "duration": 10,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "scene3d",
      "viewport"
    ],
    "htmlPath": "/bits/carousel.html"
  },
  {
    "id": "cube-navigation",
    "name": "Cube Navigation 3D",
    "title": "Cube Navigation 3D",
    "description": "Navigate through faces of a 3D Cube using Scene3D steps",
    "category": "scenes-3d",
    "categoryLabel": "3D Scenes",
    "tags": [
      "3d",
      "cube",
      "navigation",
      "camera",
      "isometric"
    ],
    "duration": 16,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "scene3d",
      "viewport"
    ],
    "htmlPath": "/bits/cube-navigation.html"
  },
  {
    "id": "cursor-flyover",
    "name": "Cursor Flyover",
    "title": "Cursor Flyover",
    "description": "Camera flies over an app screenshot while a cursor highlights different areas",
    "category": "scenes-3d",
    "categoryLabel": "3D Scenes",
    "tags": [
      "3d",
      "camera",
      "cursor",
      "screenshot",
      "presentation"
    ],
    "duration": 10,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "scene3d",
      "viewport"
    ],
    "htmlPath": "/bits/cursor-flyover.html"
  },
  {
    "id": "flying-through-words",
    "name": "Flying Through Words",
    "title": "Flying Through Words",
    "description": "Words spawning and flying past the camera",
    "category": "scenes-3d",
    "categoryLabel": "3D Scenes",
    "tags": [
      "particles",
      "text",
      "3d",
      "flythrough"
    ],
    "duration": 10,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "scene3d",
      "viewport"
    ],
    "htmlPath": "/bits/flying-through-words.html"
  },
  {
    "id": "ken-burns",
    "name": "Ken Burns Effect",
    "title": "Ken Burns Effect",
    "description": "Slow camera movement over images using Scene3D steps",
    "category": "scenes-3d",
    "categoryLabel": "3D Scenes",
    "tags": [
      "scene-3d",
      "camera",
      "ken-burns",
      "motion"
    ],
    "duration": 10,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "viewport"
    ],
    "htmlPath": "/bits/ken-burns.html"
  },
  {
    "id": "step-timing-context",
    "name": "Step-Aware Motion Timing",
    "title": "Step-Aware Motion Timing",
    "description": "Demonstrates useMotionTiming context awareness in Scene3D Steps",
    "category": "scenes-3d",
    "categoryLabel": "3D Scenes",
    "tags": [
      "3d",
      "timing",
      "animation",
      "context"
    ],
    "duration": 10,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "scene3d",
      "stagger",
      "text",
      "viewport"
    ],
    "htmlPath": "/bits/step-timing-context.html"
  },
  {
    "id": "terminal-3d",
    "name": "3D Terminal",
    "title": "3D Terminal",
    "description": "A 3D scene with multiple terminal windows executing commands.",
    "category": "scenes-3d",
    "categoryLabel": "3D Scenes",
    "tags": [
      "3d",
      "terminal",
      "typewriter",
      "code"
    ],
    "duration": 10,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "scene3d",
      "text",
      "viewport"
    ],
    "htmlPath": "/bits/terminal-3d.html"
  },
  {
    "id": "transform3d-showcase",
    "name": "Transform3D Showcase",
    "title": "Transform3D Showcase",
    "description": "Demonstrates chainable Transform3D API with matrix-based interpolation, relative transforms, and smooth quaternion rotations",
    "category": "scenes-3d",
    "categoryLabel": "3D Scenes",
    "tags": [
      "3d",
      "transform",
      "matrix",
      "quaternion",
      "chainable"
    ],
    "duration": 16.67,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "scene3d",
      "viewport"
    ],
    "htmlPath": "/bits/transform3d-showcase.html"
  },
  {
    "id": "card-stack",
    "name": "3D Card Stack",
    "title": "3D Card Stack",
    "description": "A stack of cards that spreads out in 3D space.",
    "category": "staggered-motion",
    "categoryLabel": "Staggered Motion",
    "tags": [
      "3d",
      "motion",
      "staggered-motion",
      "cards"
    ],
    "duration": 4,
    "width": 1080,
    "height": 1080,
    "helpers": [
      "viewport"
    ],
    "htmlPath": "/bits/card-stack.html"
  },
  {
    "id": "chat-conversation",
    "name": "Chat Conversation",
    "title": "Chat Conversation",
    "description": "Messaging-app style conversation with bubbles arriving one after another.",
    "category": "staggered-motion",
    "categoryLabel": "Staggered Motion",
    "tags": [
      "chat",
      "messages",
      "ui",
      "staggered-motion",
      "product-demo"
    ],
    "duration": 5,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "stagger",
      "viewport"
    ],
    "htmlPath": "/bits/chat-conversation.html"
  },
  {
    "id": "easings-visualizer",
    "name": "Easings Visualizer",
    "title": "Easings Visualizer",
    "description": "Visualizes different easing functions with sliding squares.",
    "category": "staggered-motion",
    "categoryLabel": "Staggered Motion",
    "tags": [
      "easing",
      "motion",
      "staggered-motion"
    ],
    "duration": 3,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "viewport"
    ],
    "htmlPath": "/bits/easings-visualizer.html"
  },
  {
    "id": "fracture-reassemble",
    "name": "Fracture Reassemble",
    "title": "Fracture Reassemble",
    "description": "Grid of tiles shatters into 3D space and reassembles with abstract symbol accents",
    "category": "staggered-motion",
    "categoryLabel": "Staggered Motion",
    "tags": [
      "motion",
      "staggered-motion",
      "fracture",
      "3d",
      "transition"
    ],
    "duration": 6,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "random",
      "viewport"
    ],
    "htmlPath": "/bits/fracture-reassemble.html"
  },
  {
    "id": "grid-stagger",
    "name": "Grid Stagger",
    "title": "Grid Stagger",
    "description": "A grid of elements staggering in from the center using scale and opacity.",
    "category": "staggered-motion",
    "categoryLabel": "Staggered Motion",
    "tags": [
      "grid",
      "motion",
      "staggered-motion",
      "scale"
    ],
    "duration": 3,
    "width": 1080,
    "height": 1080,
    "helpers": [
      "stagger",
      "viewport"
    ],
    "htmlPath": "/bits/grid-stagger.html"
  },
  {
    "id": "list-reveal",
    "name": "List Reveal",
    "title": "List Reveal",
    "description": "A vertical list of items scaling and finding their place.",
    "category": "staggered-motion",
    "categoryLabel": "Staggered Motion",
    "tags": [
      "list",
      "motion",
      "staggered-motion",
      "ui"
    ],
    "duration": 3,
    "width": 1080,
    "height": 1080,
    "helpers": [
      "stagger",
      "viewport"
    ],
    "htmlPath": "/bits/list-reveal.html"
  },
  {
    "id": "lower-third",
    "name": "Lower Third",
    "title": "Lower Third",
    "description": "Broadcast-style name and title card that slides in, holds, and slides out.",
    "category": "staggered-motion",
    "categoryLabel": "Staggered Motion",
    "tags": [
      "lower-third",
      "title",
      "broadcast",
      "text",
      "staggered-motion",
      "ui"
    ],
    "duration": 5,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "viewport"
    ],
    "htmlPath": "/bits/lower-third.html"
  },
  {
    "id": "mosaic-reframe",
    "name": "Mosaic Reframe",
    "title": "Mosaic Reframe",
    "description": "Twelve image tiles transition from a grid to a feature mosaic, then into a diagonal cascade",
    "category": "staggered-motion",
    "categoryLabel": "Staggered Motion",
    "tags": [
      "motion",
      "staggered-motion",
      "mosaic",
      "grid",
      "layout"
    ],
    "duration": 9,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "viewport"
    ],
    "htmlPath": "/bits/mosaic-reframe.html"
  },
  {
    "id": "slide-from-left",
    "name": "Slide from Left",
    "title": "Slide from Left",
    "description": "Text that slides in from the left with fade-in effect",
    "category": "staggered-motion",
    "categoryLabel": "Staggered Motion",
    "tags": [
      "text",
      "slide",
      "motion"
    ],
    "duration": 3,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "viewport"
    ],
    "htmlPath": "/bits/slide-from-left.html"
  },
  {
    "id": "staggered-fade-in",
    "name": "Staggered Fade In",
    "title": "Staggered Fade In",
    "description": "Elements fading in sequentially",
    "category": "staggered-motion",
    "categoryLabel": "Staggered Motion",
    "tags": [
      "motion",
      "stagger",
      "fade"
    ],
    "duration": 3,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "stagger",
      "viewport"
    ],
    "htmlPath": "/bits/staggered-fade-in.html"
  },
  {
    "id": "bar-chart",
    "name": "Bar Chart",
    "title": "Bar Chart",
    "description": "Horizontal bar chart growing in with staggered bars and counting values.",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "chart",
      "data",
      "stats",
      "counter",
      "staggered-motion",
      "ui"
    ],
    "duration": 4,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "stagger",
      "counter",
      "viewport"
    ],
    "htmlPath": "/bits/bar-chart.html"
  },
  {
    "id": "basic-code-block",
    "name": "Basic Code Block",
    "title": "Basic Code Block",
    "description": "Syntax highlighted code with line-by-line reveal",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "code",
      "animation"
    ],
    "duration": 4,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "code",
      "stagger",
      "viewport"
    ],
    "htmlPath": "/bits/basic-code-block.html"
  },
  {
    "id": "basic-counter",
    "name": "Basic Counter",
    "title": "Basic Counter",
    "description": "Animated counter interpolating between numbers.",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "counter",
      "numbers"
    ],
    "duration": 4,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "counter",
      "viewport"
    ],
    "htmlPath": "/bits/basic-counter.html"
  },
  {
    "id": "basic-typewriter",
    "name": "Basic Typewriter",
    "title": "Basic Typewriter",
    "description": "Simple typing animation with cursor.",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "typewriter",
      "basic"
    ],
    "duration": 5,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "text",
      "viewport"
    ],
    "htmlPath": "/bits/basic-typewriter.html"
  },
  {
    "id": "blur-slide-word",
    "name": "Blur In",
    "title": "Blur In",
    "description": "Text that fades, unblurs and slides up word by word",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "word",
      "blur",
      "slide",
      "stagger"
    ],
    "duration": 3,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "text",
      "stagger",
      "viewport"
    ],
    "htmlPath": "/bits/blur-slide-word.html"
  },
  {
    "id": "char-by-char",
    "name": "Staggered Char Animation",
    "title": "Staggered Char Animation",
    "description": "Text that appears character by character with staggered timing",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "character",
      "stagger"
    ],
    "duration": 4,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "text",
      "stagger",
      "viewport"
    ],
    "htmlPath": "/bits/char-by-char.html"
  },
  {
    "id": "cli-simulation",
    "name": "CLI Simulation",
    "title": "CLI Simulation",
    "description": "Simulates a command-line interface with user typing and system output.",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "typewriter",
      "cli",
      "terminal"
    ],
    "duration": 15,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "text",
      "viewport"
    ],
    "htmlPath": "/bits/cli-simulation.html"
  },
  {
    "id": "counter-confetti",
    "name": "Counter Confetti",
    "title": "Counter Confetti",
    "description": "Counter reaching 1000 with confetti particles bursting from the sides.",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "counter",
      "particles",
      "confetti",
      "celebration"
    ],
    "duration": 6,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "counter",
      "particles",
      "viewport"
    ],
    "htmlPath": "/bits/counter-confetti.html"
  },
  {
    "id": "fade-in",
    "name": "Fade In",
    "title": "Fade In",
    "description": "Simple fade-in text animation from transparent to opaque",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "fade",
      "basic"
    ],
    "duration": 3,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "viewport"
    ],
    "htmlPath": "/bits/fade-in.html"
  },
  {
    "id": "glitch-cycle",
    "name": "Glitch Cycle",
    "title": "Glitch Cycle",
    "description": "Cycling text with glitch transition effects between words",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "glitch",
      "cycle"
    ],
    "duration": 8,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "random",
      "viewport"
    ],
    "htmlPath": "/bits/glitch-cycle.html"
  },
  {
    "id": "glitch-in",
    "name": "Glitch In",
    "title": "Glitch In",
    "description": "Text effect that glitches into existence from random characters",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "glitch",
      "transition"
    ],
    "duration": 3,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "text",
      "random",
      "viewport"
    ],
    "htmlPath": "/bits/glitch-in.html"
  },
  {
    "id": "matrix-rain",
    "name": "Matrix Rain",
    "title": "Matrix Rain",
    "description": "Digital rain animation inspired by The Matrix",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "matrix",
      "code",
      "background"
    ],
    "duration": 10,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "random",
      "viewport"
    ],
    "htmlPath": "/bits/matrix-rain.html"
  },
  {
    "id": "multi-text-typewriter",
    "name": "Multi-Text Typewriter",
    "title": "Multi-Text Typewriter",
    "description": "Typing multiple sentences in sequence with deleting phase.",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "typewriter",
      "sequence",
      "loop"
    ],
    "duration": 10,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "text",
      "interpolate",
      "viewport"
    ],
    "htmlPath": "/bits/multi-text-typewriter.html"
  },
  {
    "id": "stat-rings",
    "name": "Stat Rings",
    "title": "Stat Rings",
    "description": "Circular progress rings filling up with percentage counters in the center.",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "chart",
      "data",
      "stats",
      "counter",
      "progress",
      "svg",
      "ui"
    ],
    "duration": 4,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "stagger",
      "counter",
      "interpolate",
      "viewport"
    ],
    "htmlPath": "/bits/stat-rings.html"
  },
  {
    "id": "typing-code-block",
    "name": "Typing Code Block",
    "title": "Typing Code Block",
    "description": "Syntax highlighted code with typing effect",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "code",
      "animation",
      "typing"
    ],
    "duration": 6,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "code",
      "text",
      "viewport"
    ],
    "htmlPath": "/bits/typing-code-block.html"
  },
  {
    "id": "variable-speed-typewriter",
    "name": "Variable Speed & Typos",
    "title": "Variable Speed & Typos",
    "description": "Advanced typewriter with variable speed curves and error simulation.",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "typewriter",
      "speed",
      "errors"
    ],
    "duration": 13.33,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "text",
      "random",
      "interpolate",
      "viewport"
    ],
    "htmlPath": "/bits/variable-speed-typewriter.html"
  },
  {
    "id": "word-by-word",
    "name": "Word by Word",
    "title": "Word by Word",
    "description": "Animated text that appears word by word with staggered timing",
    "category": "text-animations",
    "categoryLabel": "Text Animations",
    "tags": [
      "text",
      "word",
      "stagger"
    ],
    "duration": 4,
    "width": 1920,
    "height": 1080,
    "helpers": [
      "text",
      "stagger",
      "viewport"
    ],
    "htmlPath": "/bits/word-by-word.html"
  }
];

export const docsBitsById: Record<string, DocsBit> = Object.fromEntries(
  docsBits.map((bit) => [bit.id, bit]),
);
